### ISSUE TITLE
result is null

### ISSUE THREAD

**Issue by lilili123lj** [AxelitoMartin/OncoCast#39]
Dear author,
       hello,I have some problem about oncoCast. I need your help.
       Question:continuous variable（such as age,TMB）,what should I do with them? when I use the data on https://tinyurl.com/yd3ujxwv,I can get low/high risk groups.
![image](https://user-images.githubusercontent.com/109207607/178707834-9fce50e4-8c36-4bfb-b98e-b68cdaf7c339.png)

But when I use R packages OncoCast,I got the result were null
![image](https://user-images.githubusercontent.com/109207607/178707441-60b6b93c-450a-4088-a847-206d6e87e78d.png)

![image](https://user-images.githubusercontent.com/109207607/178707257-b80567ff-88a1-4aba-8c7a-01fb5a104ebb.png),

onco_run <- OncoCast(data = oncodata, family = "cox", formula = Surv(OS,OS_status)~., method = c("LASSO"),
                     runs = 50, cores = 1, save = FALSE
)
Why the result is NULL?How can I solve this problem? Is the web page result  correct?

**Comment by AxelitoMartin** [comment]
Hi, 
Thank you for your feedback. 
Continuous variables should be dichotomized (in whatever fashion you prefer) into dummy binary variables. 
The OncoCast function actually has an internal process that performs this task for categorical variables and continuous variables but I must have not updated the app functions to perform this task as well. 
Are you using the online platform or the internal application of the package? (So I know where to perform the update).

Thanks again, I hope this was helpful!

**Comment by lilili123lj** [comment]
Hello,
Thank you for your review.
I use two online platform(https://tinyurl.com/yd3ujxwv and https://axelitomartin.shinyapps.io/OncoCast/?_ga=2.124850764.733046146.1606492754-1896886074.1572897510),and I also use the R package OncoCast! 
Thanks again, your review was useful!

**Comment by AxelitoMartin** [comment]
Hello, sorry for the delay, currently traveling in Europe. 
But I see, so the application for the OncoCast-MPM is linked to a specific melanoma paper (that you can find here: https://www.sciencedirect.com/science/article/pii/S2589750021001047) so if you should use this one if you working within that disease, otherwise you should use the general OncoCast that can learn from the provided data (as seen in the second link you provided). 
Anyway, I will make sure to fix all of this when I get back from vacation and thanks again for brining it to my attention! Hope the quick fix I suggested above worked for you!
